stages:
  get-features:
    cmd: python3 scripts/get_features.py train.csv
    deps:
    - train.csv
    - scripts/get_features.py
    outs:
    - data/stage1
  fill-na:
    cmd: python3 scripts/fill_na.py  data/stage1/train.csv
    deps:
    - data/stage1/train.csv
    - scripts/fill_na.py
    outs:
    - data/stage2
  change_text:
    cmd: python3 scripts/change_text_to_numeric.py data/stage2/train.csv
    deps:
    - data/stage2/train.csv
    - scripts/change_text_to_numeric.py
    outs:
    - data/stage3
  split:
    cmd: python3 scripts/train_test_split.py data/stage3/train.csv
    deps:
    - data/stage3/train.csv
    - scripts/train_test_split.py
    outs:
    - data/stage4
  train:
    cmd: python3 model/dt.py data/stage4/train.csv model.pkl
    deps:
      - data/stage4/train.csv
      - model/dt.py
    params:
      - train.seed
      - train.normalize
    outs:
      - models/model.pkl
  